# Configurations and variables for Shikra SoC family.

SOC_FAMILY = "shikra"
require conf/machine/include/qcom-base.inc
require conf/machine/include/qcom-common.inc

DEFAULTTUNE = "armv8-2a-crypto"
require conf/machine/include/arm/arch-armv8-2a.inc

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += " \
    packagegroup-qcom-boot-essential \
    packagegroup-machine-essential-qcom-shikra-soc \
"

MACHINE_EXTRA_RRECOMMENDS += " \
    packagegroup-qcom-boot-additional \
"

QCOM_UBOOT_SPL_ENTRY ?= "0x0C219000"

UBOOT_FIT_ARM_TRUSTED_FIRMWARE_LOADADDRESS ?= "0xA1300000"
UBOOT_FIT_ARM_TRUSTED_FIRMWARE_ENTRYPOINT ?= "0xA1300000"

UBOOT_FIT_TEE_LOADADDRESS ?= "0xA1400000"
UBOOT_FIT_TEE_ENTRYPOINT ?= "0xA1400000"

UBOOT_FIT_UBOOT_LOADADDRESS ?= "0x87980000"
UBOOT_FIT_UBOOT_ENTRYPOINT ?= "0x87980000"

# Recipes providing BL31 and OP-TEE for the FIT
QCOM_UBOOT_SPL_FIT_ATF ?= "trusted-firmware-a-qcom-shikra"
QCOM_UBOOT_SPL_FIT_TEE ?= "optee-os-qcom-shikra"

